version: "3.3"

services:
# Base de Datos MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./dbsql/carmakers.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - 3306
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: carmakers
    networks:
      - app-network
# Aplicacion Node
  app:
    image: node:16
    container_name: nodeapp
    command: npm start
    ports:
      - "6000:8080"
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mysql  
    links:
      - "mysql:carmakers"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: carmakers
    networks:
      - app-network
# redes de los contenedores
networks:
  app-network:
    driver: bridge


# 6*21391
# 9600

